---
name: predbat
version: 1.1.13
slug: predbat
description: Home Battery Prediction and Control
url: https://github.com/springfall2008/predbat_addon
codenotary: tdlj@tdlj.net
webui: http://[HOST]:[PORT:8099]
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
hassio_api: true
hassio_role: admin
auth_api: true
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Predbat
ingress: true
ingress_entry: dashboard/  
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  dummy: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  dummy:
    - str
